export function exportQuizToPdf(title: string, questions: any[], withAnswers: boolean) {
  const printWindow = window.open("", "_blank");
  if (!printWindow) {
    alert("Please allow popups to download PDF.");
    return;
  }

  const questionsHtml = questions.map((q, idx) => {
    const optionsHtml = q.options.map((opt: string, optIdx: number) => {
      const labels = ["A", "B", "C", "D"];
      const isCorrect = q.correctIndex === optIdx;
      const isSelectedStyle = withAnswers && isCorrect 
        ? "font-weight: bold; color: #10b981; background: #ecfdf5; border-color: #10b981;"
        : "";
      return `
        <div style="padding: 10px; border: 1px solid #e2e8f0; margin-top: 6px; border-radius: 6px; font-size: 13px; ${isSelectedStyle}">
          <strong>${labels[optIdx] || optIdx + 1}.</strong> ${opt}
          ${withAnswers && isCorrect ? ' <span style="font-size: 10px; font-weight: bold; margin-left: 8px; color: #10b981;">(Correct Answer)</span>' : ''}
        </div>
      `;
    }).join("");

    const explanationHtml = withAnswers && q.explanation
      ? `
        <div style="margin-top: 10px; padding: 12px; background: #f8fafc; border-left: 4px solid #6366f1; border-radius: 4px; font-size: 12px; color: #475569; line-height: 1.5;">
          <strong>AI Explanation:</strong> ${q.explanation}
        </div>
      `
      : "";

    return `
      <div style="margin-bottom: 25px; page-break-inside: avoid;">
        <h3 style="font-size: 15px; font-weight: bold; margin-bottom: 8px; color: #1e293b;">
          ${idx + 1}. ${q.question}
        </h3>
        <div style="margin-bottom: 10px;">${optionsHtml}</div>
        ${explanationHtml}
      </div>
    `;
  }).join("");

  const html = `
    <html>
      <head>
        <title>${title}</title>
        <style>
          body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 40px; color: #1e293b; line-height: 1.6; }
          h1 { font-size: 24px; font-weight: 800; border-bottom: 2px solid #e2e8f0; padding-bottom: 12px; margin-bottom: 30px; color: #0f172a; }
          .meta { font-size: 12px; color: #64748b; margin-top: -20px; margin-bottom: 30px; }
          @media print {
            body { padding: 0; }
            @page { margin: 2cm; }
          }
        </style>
      </head>
      <body>
        <h1>${title}</h1>
        <div class="meta">
          Generated by LearnForge &bull; Exported ${withAnswers ? "with Answers & Explanations" : "without Answers"} &bull; Date: ${new Date().toLocaleDateString()}
        </div>
        <div>${questionsHtml}</div>
        <script>
          window.onload = function() {
            window.print();
            setTimeout(function() { window.close(); }, 500);
          };
        </script>
      </body>
    </html>
  `;

  printWindow.document.write(html);
  printWindow.document.close();
}

export function exportFlashcardsToPdf(docName: string, flashcards: any[], withAnswers: boolean) {
  const printWindow = window.open("", "_blank");
  if (!printWindow) {
    alert("Please allow popups to download PDF.");
    return;
  }

  const cardsHtml = flashcards.map((fc, idx) => {
    const backHtml = withAnswers
      ? `
        <div style="margin-top: 12px; padding: 12px; background: #f8fafc; border-top: 1px dashed #e2e8f0; font-size: 13px; color: #334155; line-height: 1.5;">
          <strong>Answer:</strong> ${fc.back}
        </div>
      `
      : `
        <div style="margin-top: 25px; border-top: 1px dashed #e2e8f0; padding-top: 12px;">
          <span style="font-size: 10px; color: #94a3b8; font-weight: bold; text-transform: uppercase;">Write your answer here:</span>
          <div style="height: 60px; border: 1px dashed #cbd5e1; margin-top: 8px; border-radius: 4px;"></div>
        </div>
      `;

    return `
      <div style="border: 2px solid #cbd5e1; border-radius: 12px; margin-bottom: 20px; page-break-inside: avoid; overflow: hidden; background: white;">
        <div style="padding: 15px; background: #f1f5f9; font-size: 11px; font-weight: bold; text-transform: uppercase; tracking-wider; color: #475569; display: flex; justify-content: space-between; border-bottom: 1px solid #e2e8f0;">
          <span>Card #${idx + 1}</span>
          <span style="color: #6366f1;">LearnForge Flashcards</span>
        </div>
        <div style="padding: 20px;">
          <h3 style="font-size: 15px; font-weight: bold; margin: 0; color: #1e293b;">
            ${fc.front}
          </h3>
          ${backHtml}
        </div>
      </div>
    `;
  }).join("");

  const html = `
    <html>
      <head>
        <title>Flashcards: ${docName}</title>
        <style>
          body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 40px; color: #1e293b; line-height: 1.6; background: #f8fafc; }
          h1 { font-size: 24px; font-weight: 800; border-bottom: 2px solid #e2e8f0; padding-bottom: 12px; margin-bottom: 30px; color: #0f172a; }
          .meta { font-size: 12px; color: #64748b; margin-top: -20px; margin-bottom: 30px; }
          @media print {
            body { padding: 0; background: none; }
            @page { margin: 1.5cm; }
          }
        </style>
      </head>
      <body>
        <h1>Study Deck: ${docName}</h1>
        <div class="meta">
          Generated by LearnForge &bull; Exported ${withAnswers ? "with Answers" : "without Answers"} &bull; Total Cards: ${flashcards.length} &bull; Date: ${new Date().toLocaleDateString()}
        </div>
        <div style="display: grid; grid-template-columns: 1fr; gap: 15px;">${cardsHtml}</div>
        <script>
          window.onload = function() {
            window.print();
            setTimeout(function() { window.close(); }, 500);
          };
        </script>
      </body>
    </html>
  `;

  printWindow.document.write(html);
  printWindow.document.close();
}
